Models/AdminPanelModel.cs
namespace TestKSK.Models
{
    public class AdminPanelModel
    {
        public uint UserBalance { get; set; }
        public BeverageModel[] Beverages { get; set; }
        public MoneyUnitModel[] MoneyUnits { get; set; }
    }
}

Models/BeverageModel.cs
namespace TestKSK.Models
{
    public class BeverageModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public uint Price { get; set; }
        public uint Count { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace TestKSK.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MoneyUnitModel.cs
namespace TestKSK.Models
{
    public class MoneyUnitModel
    {
        public Guid Id { get; set; }
        public uint Denomination { get; set; }
        public bool IsAvailable { get; set; }
    }
}

Models/Requests/BeverageBuyRequest.cs
namespace TestKSK.Models.Requests
{
    public class BeverageBuyRequest
    {
        public Guid Id { get; set; }
    }
}

Models/Requests/UpdateBalanceRequest.cs
namespace TestKSK.Models.Requests
{
    public class UpdateBalanceRequest
    {
        public uint Denomination { get; set; }
    }
}

Models/Requests/UpdateMoneyUnitAvailabilityRequest.cs
namespace TestKSK.Models.Requests
{
    public class UpdateMoneyUnitAvailabilityRequest
    {
        public uint Denomination { get; set; }
    }
}

Models/Results/BeverageBuyResult.cs
namespace TestKSK.Models.Results
{
    public class BeverageBuyResult : UserActionResult
    {
        public uint Change { get; set; }
    }
}

Models/Results/UserActionResult.cs
namespace TestKSK.Models
{
    public class UserActionResult
    {
        public bool Succeeded { get; set; }
        public string? ErrorMsg { get; set; }
    }
}

Models/VendingMachineModel.cs
namespace TestKSK.Models
{
    public class VendingMachineModel
    {
        public Guid Id { get; set; }
        public uint UserBalance { get; set; }
        public BeverageModel[] Beverages { get; set; }
        public MoneyUnitModel[] MoneyUnits { get; set; }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestKSK.Interfaces;
using TestKSK.Models;
using TestKSK.Models.Requests;
using TestKSK.Services;

namespace TestKSK.Controllers
{
    //[Authorize]
    public class AdminController : Controller
    {
        private readonly IVendingMachineService vendingMachineService;

        public AdminController(IVendingMachineService vendingMachineService)
        {
            this.vendingMachineService = vendingMachineService;
        }

        [HttpGet("/admin")]
        public async Task<ActionResult> Index()
        {
            var adminModel = await vendingMachineService.GetAdminModel();
            return View(adminModel);
        }

        [HttpGet("/admin/add-beverage")]
        public async Task<ActionResult> AddBeverage()
        {
            return View();
        }

        [HttpPost("/admin/add-beverage")]
        public async Task<ActionResult> AddBeverage(BeverageModel model)
        {
            var result = await vendingMachineService.AddBeverage(model);
            if (result.Succeeded)
                return Ok();
            return BadRequest(result.ErrorMsg);
        }

        [HttpGet("/admin/edit-beverage/{id}")]
        public async Task<ActionResult> EditBeverage([FromRoute] Guid Id)
        {
            var beverage = await vendingMachineService.GetBeverageModel(Id);
            return View(beverage);
        }

        [HttpPost("/admin/edit-beverage/{id}")]
        public async Task<ActionResult> EditBeverage(BeverageModel model)
        {
            var result = await vendingMachineService.EditBeverage(model);
            if (result.Succeeded)
                return Redirect("/admin");
            return BadRequest(result.ErrorMsg);
        }

        [HttpPost("update-unit-availability")]
        public async Task<ActionResult> ChangeMoneyUnitAvailability(
            [FromBody] UpdateMoneyUnitAvailabilityRequest request)
        {
            var result = await vendingMachineService
                .SwitchMoneyUnitAvailability(request);
            if (result.Succeeded)
                return Redirect("/admin");
            return BadRequest(result.ErrorMsg);
        }
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using TestKSK.Interfaces;

namespace TestKSK.Controllers
{
    public class AuthController : Controller
    {
        private readonly IJwtService jwtService;

        public AuthController(IJwtService jwtService)
        {
            this.jwtService = jwtService;
        }

        [HttpGet("/get-token")]
        public async Task<string> GetAuthToken()
        {
            //TODO
            var claims = new List<(string, string)> {
                (JwtRegisteredClaimNames.NameId, "TestUsername"),
            };

            return jwtService.CreateToken(claims);
        }
    }
}

Controllers/VendingMachineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestKSK.Interfaces;
using TestKSK.Models.Requests;

namespace TestKSK.Controllers
{
    public class VendingMachineController : Controller
    {
        private readonly IVendingMachineService vendingMachineService;

        public VendingMachineController(IVendingMachineService vendingMachineService)
        {
            this.vendingMachineService = vendingMachineService;
        }

        public async Task<ActionResult> Index()
        {
            var machineModel = await vendingMachineService.GetVendingMachineModel();
            return View(machineModel);
        }

        [HttpPost("update-balance")]
        public async Task<ActionResult> UpdateBalance([FromBody] UpdateBalanceRequest request)
        {
            var result = await vendingMachineService.UpdateUserBalance(request);
            if (result.Succeeded)
                return Ok();
            return BadRequest(result.ErrorMsg);
        }

        [HttpPost("buy-beverage")]
        public async Task<ActionResult> BuyBeverage(BeverageBuyRequest request)
        {
            var result = await vendingMachineService.BuyBeverage(request);
            if (result.Succeeded)
                return Ok($"Ваша сдача: {result.Change} ₽");
            return BadRequest(result.ErrorMsg);
        }
    }
}

Views/Admin/AddBeverage.cshtml
@model TestKSK.Models.BeverageModel

@{
    ViewData["Title"] = "Создание напитка";
}

<h1>Создание напитка</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBeverage" class="custom-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена в рублях</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label">Колличество напитков</label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад на панель</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Admin/EditBeverage.cshtml
@model TestKSK.Models.BeverageModel

@{
    ViewData["Title"] = "Редактирование напитка";
}

<h1>Редактировать напиток</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBeverage" class="custom-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена в рублях</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Count" class="control-label">Колличество напитков</label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад на панель</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Административная панель";
}

@model AdminPanelModel;

<div class="text-center">
    <h1 class="display-4">Административная панель</h1>
    <div class="flex-container beverages">
        @foreach (var beverage in Model.Beverages)
        {
            <div class="admin-beverage">
                <h3>@beverage.Name</h3>
                <h4>@beverage.Price ₽</h4>
                <h6>@beverage.Count</h6>
                <div>
                    <a href="@($"/admin/edit-beverage/{beverage.Id}")">Редактировать напиток</a>
                </div>
            </div>
        }
    </div>
    <div class="flex-container beverage-adding-ref">
        <a href="/admin/add-beverage">Добавить напиток</a>
    </div>
    <div class="flex-container money-unit-buttons">
        @foreach(var moneyUnit in Model.MoneyUnits)
        {
            <div>
                <button id="@(moneyUnit.Denomination)"
                class="admin-money-unit-btn @(moneyUnit.IsAvailable ? "active" : "")"
                onclick="changeMoneyUnitAvailability(@moneyUnit.Denomination)">
                    @moneyUnit.Denomination ₽
                </button>
            </div>
        }
    </div>
    <div id="balance-display-container">
        Текущий баланс: @Model.UserBalance ₽
    </div>
</div>

<script type="text/javascript" src="@Url.Content("/js/admin.js")"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestKSK.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestKSK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VendingMachine" asp-action="Index">Торговый автомат</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/admin?secretToken=token">Административная панель</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestKSK
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/VendingMachine/Index.cshtml
@{
    ViewData["Title"] = "Торговый автомат";
}

@model VendingMachineModel;

<div class="text-center">
    <h1 class="display-4">Торговый автомат</h1>
    <div class="flex-container beverages">
        @foreach (var beverage in Model.Beverages)
        {
            <form asp-action="BuyBeverage" class="custom-form">
                <input type="hidden" asp-for="Id" value="@beverage.Id"/>
                <div>
                    <button class="beverage-btn" type="submit">
                        <h3>@beverage.Name</h3>
                        <h4>@beverage.Price ₽</h4>
                        <h6>@beverage.Count</h6>
                    </button>
                </div>
            </form>
        }
    </div>
    <div class="flex-container money-unit-buttons">
        @foreach(var moneyUnit in Model.MoneyUnits)
        {
            <div>
                <button 
                disabled="@(!moneyUnit.IsAvailable)"
                class="money-unit-btn" 
                onclick="onMoneyUnitClick(@moneyUnit.Denomination)">
                    @moneyUnit.Denomination ₽
                </button>
            </div>
        }
    </div>
    <div>
        Текущий баланс:
        <div style="display: inline-block;" id="balance-display-container">
            @Model.UserBalance
        </div> 
        ₽
    </div>
</div>

<script type="text/javascript" src="@Url.Content("/js/vending.js")"></script>